name: deep_rl
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7.16
  - numpy
  - matplotlib
  - opencv
  - pip
  - pip:
      - atari-py==0.2.6
      - gym==0.17.3
      - tensorboard==2.4.0
      - torch==1.7.0
      - torchvision==0.8.1
      - pytorch-ignite==0.4.2
      - tensorboardX==2.1
      - tensorflow==2.3.1
      - nltk==3.5
      - pybullet==3.0.7
      - ptan==0.7
      - protobuf==3.20
