name: deep_rl
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2024.12.31
  - certifi=2022.12.7
  - cudatoolkit=9.0
  - freetype=2.12.1
  - giflib=5.2.2
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lcms2=2.16
  - lerc=4.0.0
  - libcxx=14.0.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libpng=1.6.39
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - ninja=1.12.1
  - ninja-base=1.12.1
  - openssl=1.1.1w
  - pillow=9.4.0
  - pip=22.3.1
  - python=3.7.16
  - pytorch=1.7.0
  - readline=8.2
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.45.3
  - tk=8.6.14
  - torchaudio=0.7.0
  - torchvision=0.8.1
  - typing_extensions=4.3.0
  - wheel=0.38.4
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - absl-py==2.1.0
    - astunparse==1.6.3
    - atari-py==0.2.6
    - cachetools==4.2.4
    - charset-normalizer==3.4.1
    - click==8.1.8
    - cloudpickle==1.6.0
    - cycler==0.11.0
    - dataclasses==0.6
    - fonttools==4.38.0
    - future==1.0.0
    - gast==0.3.3
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.62.3
    - gym==0.17.3
    - h5py==2.10.0
    - idna==3.10
    - importlib-metadata==6.7.0
    - joblib==1.3.2
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.5
    - markdown==3.4.4
    - markupsafe==2.1.5
    - matplotlib==3.5.3
    - nltk==3.5
    - numpy==1.18.5
    - oauthlib==3.2.2
    - opencv-python==4.4.0.46
    - opt-einsum==3.3.0
    - packaging==24.0
    - protobuf==3.20.0
    - ptan==0.7
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pybullet==3.0.7
    - pyglet==1.5.0
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - pytorch-ignite==0.4.2
    - regex==2024.4.16
    - requests==2.31.0
    - requests-oauthlib==2.0.0
    - rsa==4.9
    - scipy==1.7.3
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.1
    - tensorflow==2.3.1
    - tensorflow-estimator==2.3.0
    - termcolor==2.3.0
    - tqdm==4.67.1
    - urllib3==2.0.7
    - werkzeug==2.2.3
    - wrapt==1.16.0
    - zipp==3.15.0
